export const STALL_ERROR_NOT_FOUND = "Stall was not found!";
export const STALL_STATUS = {
  AVAILABLE: "AVAILABLE",
  OCCUPIED: "OCCUPIED",
  UPCOMING: "UPCOMING",
  INMAINTENANCE: "INMAINTENANCE",
  UNAVAILABLE: "UNAVAILABLE",
};
