export const STALL_ERROR_NOT_FOUND = "Stall was not found!";
export const STALL_ERROR_NOT_AVAILABLE = "Stall not available!";
export const STALL_STATUS = {
  AVAILABLE: "AVAILABLE",
  OCCUPIED: "OCCUPIED",
  UPCOMING: "UPCOMING",
  INMAINTENANCE: "INMAINTENANCE",
  UNAVAILABLE: "UNAVAILABLE",
};
export const STALL_RATE_CODE = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
};

