export const TENANTRENTBOOKING_ERROR_NOT_FOUND = "Booking not found!";
export const TENANTRENTBOOKING_STATUS = {
  PENDING: "PENDING",
  REJECTED: "REJECTED",
  PROCESSING: "PROCESSING",
  LEASED: "LEASED",
  CANCELLED: "CANCELLED",
};
