export const TENANTRENTCONTRACT_ERROR_NOT_FOUND = "Contract not found!";

export const TENANTRENTCONTRACT_STATUS = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  RENEWED: "RENEWED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
};
